---
title: "Final Project Code"
author: "Sujit Sivadanam"
date: "2024-05-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
nba_stat <- read.csv("./nba_2023_24.csv")
```

## Removing unnecessary variables
```{r}
library(dplyr)
nba_stat <- nba_stat %>% select(-c(Rk,Tm,G,GS,FG,FG.,X3P,X3P.,X2P,X2P.,
                                   eFG.,FT,FTA,FT.,Player.additional))
```

## "Player's Style" Variable
```{r}
# 3PA/FGA
nba_stat$shoot_style <- nba_stat$X3PA/nba_stat$FGA

#Remove rows with NaNs in shoot_style
nba_stat <- nba_stat %>% filter(!is.na(shoot_style))

# Linear Model (not needed)
style_lm <- lm(PTS ~ shoot_style, nba_stat)
summary(style_lm)
```

## Multiple Linear Regression

### Original MLR
```{r}
pts_lm <- lm(PTS ~ MP+TRB+AST+STL+BLK+TOV+PF+shoot_style, nba_stat)
```

### MLR after modification (w/ 95% confidence intervals)

```{r}

```

## Logistic Regression #1

Is the player's points per game above or below league average?

```{r}
# Create "Above average or not" variable
nba_stat$Above_Avg <- ifelse(nba_stat$PTS >= mean(nba_stat$PTS), 1, 0)

# Logistic Regression
avgPTS_log <- glm(Above_Avg ~ TRB+AST+STL+BLK+TOV+PF+shoot_style,
                  nba_stat, family="binomial")
```

## Logistic Regression #2

Does a player play center position?

```{r}
# Create "center or not" variable
nba_stat$Center <- ifelse(grepl("C", nba_stat$Pos), 1, 0)

# Logistic Regression
center_log <- glm(Center ~ TRB+AST+STL+BLK+TOV+PF+shoot_style,
                  nba_stat, family="binomial")
```
